### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by mikeattara**
Fix mailer scripts for signup form

### CODE REVIEW

**Comment by MattCSmith** [comment]
Im probably missing something here, but how does this fix the issue? Since there does not appear to be any actual code change, rather than a change in formatting.

**Comment by mikeattara** [comment]
@MattCSmith This was meant to be part of the earlier PR, but you merged it to quickly. I reformat the code to make it clearer for maintainability.

**Comment by mikeattara** [comment]
You can close the PR if you strongly feel it is not necessary.

**Comment by MattCSmith** [comment]
Not at all, Im happy to merge it. I was just confused as to if it was a formatting change or a fix. 
It would also appear that the original issue may not have been solved

**Pull request merged**
