### PR TITLE
add test folder, failed at mocking require.context

### PR DESCRIPTION
**Pull request by Aszmel**
just simple tests, but failed with "require.context error is not a function", just for now can't solve it on my own how to mock this part

### CODE REVIEW

**Comment by aneagoie** [comment]
Looks like you removed the packages from package.json?

**Comment by Aszmel** [comment]
Pushing again App.test.js

**Comment by aneagoie** [comment]
Can we close this PR? Looks like we merged a PR already that sets up the tests for us

**Comment by Aszmel** [comment]
ye, sure, closing this Andrei

**Pull request closed without merging**
