### PR TITLE
zoom fix

### PR DESCRIPTION
**Pull request by mortenkos**
-added click functions to plus and minus sign
zoom works
worked in my pc :)
@aneagoie can you review this solution?

### CODE REVIEW

**Comment by aneagoie** [comment]
Nicely done! 👍

**Comment by aneagoie** [comment]
Just noticed.. `-` doesn't seem to be working @mortenkos

**Comment by mortenkos** [comment]
@aneagoie 
I will try to find this bug. 
Noticed that it works if the screen size is below 1200px

**Comment by mortenkos** [comment]
found it. chart is overlapping minus sign

**Comment by aneagoie** [comment]
A bit of a hack, but if you set:
.zoombox class to z-index: 1, it will fix this issue

**Comment by mortenkos** [comment]
I did it with z-index 1000 :D

**Comment by aneagoie** [comment]
Let's keep it at 1 so we don't confuse people :)

**Comment by mortenkos** [comment]
That's a reasonable decision. Made that change :)

**Pull request merged**
