### PR TITLE
responsive toolbox and chart

### PR DESCRIPTION
**Pull request by mortenkos**
My version of the toolbox.  @MattCSmith 

untitled

### CODE REVIEW

**Comment by The24thDS** [comment]
@mortenkos It seems we have some conflicting files :)

**Comment by mortenkos** [comment]
@The24thDS now it should be ok :)

**Comment by mortenkos** [comment]
@The24thDS  I think that after this PR you can close #191 & #192 :)

**Comment by The24thDS** [comment]
Can you add a magnifying glass instead of the zoom text? 😄 Or I am asking too much at this point? 😆

**Comment by mortenkos** [comment]
untitled

**Comment by The24thDS** [comment]
Best I ever saw. 👍 You did a fantastic job with this one. I am more mechanical than artistic but it seems that you got both of them 🥇

**Comment by mortenkos** [comment]
Woww thanks. I never considered myself as an artistic person and always thought that I don't have an eye for this.
So thanks for boosting my self-confidence :) @The24thDS

**Comment by mortenkos** [comment]
@The24thDS  I noticed a few bugs(with zoom slider) with this layout in my Samsung mobile. But unfortunately, I don't have time to deal with this today

**Comment by The24thDS** [comment]
We will take it from here, no worries man. You did a good job :)

**Pull request merged**
