### PR TITLE
fix: all contributors RC file users

### PR DESCRIPTION
**Pull request by jakebolam**
Follow up to #181

### CODE REVIEW

**Comment by The24thDS** [comment]
@jakebolam I think at this moment is best to give you guys a bit of time to come up with an update to make this easier as our tries seem to fail. Thank you for your support with this 🥇

**Comment by jakebolam** [comment]
Thanks, @The24thDS appreciated. Thanks for being one of the first users :)

**Comment by jakebolam** [comment]
@allcontributors[bot] please add @jakebolam for infrastructure

**Comment by jakebolam** [comment]
@The24thDS back in business (the PR above fixes the table too!)
https://github.com/zeroDevs/coding_challenge-13/blob/4979ae70d9c2c27905d6f64f1231c3209235ae09/README.md

Bunch of work in-progress/todo now as a result of the usage here :)

**Pull request merged**
