### PR TITLE
fixed warning about key required for child element

### PR DESCRIPTION
**Pull request by leighd2008**
added the uniqid package to generate key for hearts array from issue #119

### CODE REVIEW

**Comment by aneagoie** [comment]
Instead we can just generate 5 keys for the hearts for the reason Matt mentioned.

**Comment by leighd2008** [comment]
Makes sense I will make the changes.

**Comment by leighd2008** [comment]
This fix now does not include the addition of a new package. Is this what you had in mind?

**Comment by aneagoie** [comment]
Yes, well done @leighd2008 . Just a heads up that you have to remove the packages from the package.json file as well

**Comment by leighd2008** [comment]
I have removed the uniqid package from package.json

**Comment by MattCSmith** [comment]
Thats brilliant @leighd2008, although there is a conflict, could you kindly resolve so that we can merge :)

**Comment by leighd2008** [comment]
No problem @MattCSmith I'm new to this and wasn't sure if I should resolve the conflict or leave it for you to see. XD

**Comment by MattCSmith** [comment]
No problem @leighd2008, Generally speaking your good to fix any conflicts that arise when you merge.

**Pull request merged**
