### PR TITLE
toolbox and chart style fix

### PR DESCRIPTION
**Pull request by mortenkos**
I think that toolbox and chart will look this way better :) what you guys think @MattCSmith @The24thDS
I also made this chart responsive.
 
screenshot from 2019-01-26 22-33-02

### CODE REVIEW

**Comment by The24thDS** [comment]
Good job @mortenkos But where's the zoom slider?

**Comment by mortenkos** [comment]
I can add it back but don't you think that this zoom is not necessary at this point? :)
I think it looks cleaner this way :)

**Comment by The24thDS** [comment]
You wouldn't be able to see the Flutter numbers

**Comment by mortenkos** [comment]
Is this ok? :) @The24thDS 

screenshot from 2019-01-26 23-42-52

**Comment by The24thDS** [comment]
It looks great. But the reason I choose to put the toolbox side by side with the chart is that now you can't see the chart and change categories without scrolling and I find that not being very intuitive 😆

**Comment by mortenkos** [comment]
I agree on that :) delete this merge request and if I come up with something better then I shout you out again :rofl:

**Comment by The24thDS** [comment]
Are you also working on making it responsive?

**Comment by mortenkos** [comment]
Yes of course. But I will continue tomorrow. :)

**Comment by The24thDS** [comment]
Please consider implementing this:
https://bootsnipp.com/snippets/7ngvl
(@MattCSmith idea)

**Pull request closed without merging**
