### PR TITLE
Font and Style Edits

### PR DESCRIPTION
**Pull request by MattCSmith**
I have made a couple of edits to the fonts and general CSS, just to give it that bit of variety and to make some bits look a little nicer.

Navigation using font `Roboto Mono`:
image

Titles using font `Roboto Mono`, Checkboxes using font `Comfortaa`
Developer love - Font size made slightly smaller & using font `Comfortaa`
image

`<P>` and `<li>` Tags using font `Comfortaa`
image

image

image

### CODE REVIEW

**Comment by MattCSmith** [comment]
Any thoughts on this @mikeattara and @The24thDS ?

**Comment by mikeattara** [comment]
I will suggest you use Roboto slab for the headings and Roboto mono for the text.

**Comment by MattCSmith** [comment]
Ah yes, developer love is using Roboto condensed.

I felt that Roboto mono may have been a little heavy, for the paragraph text and checkboxes. If you compare theses:

image

image

The last one in my opinion looks a little lighter. 

And here in the checkboxes:
image

image

Again I feel the last one is a little light and less busy. 

But these are just my opinions. Happy to roll with what ever.

**Comment by The24thDS** [comment]
I really like how `Comfortaa` is looking but as I said above I don't like that Roboto condensed

**Pull request merged**
